services:
  mysql:
    container_name: my_little_bookworm_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_little_bookworm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mlb-net

volumes:
  mysql_data:

networks:
  mlb-net:
    external: true
