#!/usr/bin/bash
# Ensure that you're in the correct directory
cd my_little_bookworm

# Ensure that you're in a virtual env
source venv/bin/activate

# Run all of the tests in the part 4 project
python3 -m unittest