-- TO DO: Finish populating the books table with ~50 records, ensuring that the table matches the spec
INSERT INTO Book (id, external_id, source, title, author, cover_url, created_at, updated_at)
VALUES
(UUID(),"/works/OL69630W","openlibrary","A Little Princess","Frances Hodgson Burnett","https://covers.openlibrary.org/b/id/2328315-M.jpg",NOW(),NOW()),
(UUID(), "/works/OL29983W", "openlibrary", "Little Women", "Louisa May Alcott", "https://covers.openlibrary.org/b/id/8775559-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL1719792W", "openlibrary", "Little House on the Prairie", "Laura Ingalls Wilder", "https://covers.openlibrary.org/b/id/11277564-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL10263W", "openlibrary", "Le petit prince", "Antoine de Saint-Exupéry", "https://covers.openlibrary.org/b/id/10708272-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL69612W", "openlibrary", "The Secret Garden", "Frances Hodgson Burnett", "https://covers.openlibrary.org/b/id/12622062-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL52987W", "openlibrary", "The Very Hungry Caterpillar", "Eric Carle", "https://covers.openlibrary.org/b/id/7835968-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL1948587W", "openlibrary", "The magic Faraway Tree", "Enid Blyton", "https://covers.openlibrary.org/b/id/14605635-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL21812667W", "openlibrary", "Frozen (Disney Frozen)", "Victoria Saxon, Grace Lee, Andrea Cagol", null, NOW(), NOW()),
(UUID(), "/works/OL19870W", "openlibrary", "The Jungle Book", "Rudyard Kipling", "https://covers.openlibrary.org/b/id/3344204-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL655908W", "openlibrary", "The Night Before Christmas", "Clement Clarke Moore", "https://covers.openlibrary.org/b/id/8236410-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL1973461W", "openlibrary", "Uncle Elephant", "Arnold Lobel", "https://covers.openlibrary.org/b/id/4357988-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL71037W", "openlibrary", "The Lion, the Witch and the Wardrobe", "C. S. Lewis", "https://covers.openlibrary.org/b/id/8441376-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL42399456W", "openlibrary", "Bluey : Bluey's Little Book", "Bluey", null, NOW(), NOW()),
(UUID(), "/works/OL42402942W", "openlibrary", "Bluey : Trains", "Bluey", null, NOW(), NOW()),
(UUID(), "/works/OL37588159W", "openlibrary", "Bluey : What Games Should We Play?", "Bluey", null, NOW(), NOW()),
(UUID(), "/works/OL42393423W", "openlibrary", "Bluey : Where's the Easter Egg?", "Bluey", null, NOW(), NOW()),
(UUID(), "/works/OL106091W", "openlibrary", "Danny and the Dinosaur", "Syd Hoff", "https://covers.openlibrary.org/b/id/36107-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL20156081W", "openlibrary", "Peppa Pig", "Peppa Pig", "https://covers.openlibrary.org/b/id/8801127-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL16478069W", "openlibrary", "The three little pigs", "Paul Galdone", "https://covers.openlibrary.org/b/id/6611256-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL11629752W", "openlibrary", "Goldilocks and the three bears", "Kate Clynes", "https://covers.openlibrary.org/b/id/9257505-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL15053031W", "openlibrary", "Little Red Riding Hood", "Gebrüder Grimm [Brothers Grimm]", "https://covers.openlibrary.org/b/id/1535927-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL650933W", "openlibrary", "Possum magic", "Mem Fox, Vivas Julie, Julie Vivas", "https://covers.openlibrary.org/b/id/112761-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL650958W", "openlibrary", "Where is the green sheep?", "Mem Fox, Judy Horacek", "https://covers.openlibrary.org/b/id/113648-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL15852327W", "openlibrary", "Hairy Maclary from Donaldson's Dairy", "Lynley Dodd", "https://covers.openlibrary.org/b/id/6815361-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL807816W", "openlibrary", "Each Peach Pear Plum", "Janet Ahlberg, Allan Ahlberg", "https://covers.openlibrary.org/b/id/5375131-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL20022808W", "openlibrary", "Sheep go to sleep", "Nancy E. Shaw", "https://covers.openlibrary.org/b/id/13066119-M.jpg", NOW(), NOW()),
(UUID(), "/works/OL32442702W", "openlibrary", "Where's Spot?", "Eric Hill", "https://covers.openlibrary.org/b/id/8371258-M.jpg", NOW(), NOW());
SELECT 'Hooray, books have been seeded!' AS status;